### ISSUE TITLE
The attention visualization maps

### ISSUE THREAD

**Issue by Fulep** [ChongjianGE/CARE#1]
Can you publish the code for generating the attention map visualization, thank you very much.

**Comment by ChongjianGE** [comment]
Hi @Fulep,

Thanks for your interest in our work. We adopt the [Grad-CAM](https://arxiv.org/abs/1610.02391) to compute the network response. You can refer to the [pytorch-grad-cam repo](https://github.com/jacobgil/pytorch-grad-cam) for detailed implementation. 

If you have any problems in calculating the network response, please let me know. I may organize and upload the corresponding codes.

**Comment by ChongjianGE** [comment]
Since there are no further questions, I will close this issue. Please feel free to reopen it when necessary.
